baseURL = 'https://michaelhinz.dev'
languageCode = 'en-us'
title = 'Michael Hinz'
theme = "hugo-theme-m10c"

[services]
  [services.googleAnalytics]
    id = 'G-QCT2XJGN83'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 3


[params]
  author = "Michael Hinz"
  description = " "
  avatar = "/Michael Hinz.jpg"
  menu_item_separator = "|"
  #favicon = "/favicon.ico"
  [[params.social]]
    icon = "mail"
    name = "Email"
    url = "mailto:michaelhinz.mh@googlemail.com"    
  [[params.social]]
    icon = "brand-bluesky"
    name = "Bluesky"
    url = "https://bsky.app/profile/michaelhinz.dev"
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/kraxxi"
  